---
- name: Install dependencies
  package:
    name:
      - java-1.8.0-openjdk
      - git
    state: latest
 
- name: Download jenkins repo
  get_url:
    url: "{{ jenkins_download_url }}"
    dest: "{{ jenkins_repo_path }}"

- name: Import Jenkins CI key 
  rpm_key:
    key: "{{jenkins_key_url}}"
    state: present
 
- name: Install Jenkins
  package:
    name: jenkins
    state: latest

- name: Allow port 8080
  shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
 
- name: Start the server
  service:
    name: jenkins
    state: started
- wait_for: 
    port: 8080
...
